
 make.py started: 2016-11-02 16:33:20 /Users/leviboxell/Desktop/gslab_python/gslab_scons/tests 




Execute:  python  "run_all_tests.py" 
test_default (test_build_lyx.testbuild_lyx) ... ok
test_default (test_build_python.testbuild_python) ... ok
test_default (test_build_r.testbuild_r) ... ok
test_bad_order (test_build_stata.testbuild_stata) ... ok
test_bad_user_executable (test_build_stata.testbuild_stata) ... /bin/sh: bad_user_executable: command not found
ok
test_default (test_build_stata.testbuild_stata) ... ok
test_user_executable (test_build_stata.testbuild_stata) ... ok

----------------------------------------------------------------------
Ran 7 tests in 11.411s

OK
*** Error: First argument in `source`, bad, must be a .do file
*** Error: Stata executable not found.

 make.py ended: 2016-11-02 16:33:32
